# docker compose -f docker-compose.yml up -d

version: '3.8'

services:
  fireflyarticles:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "21000:21000"
    networks:
      - fireflynet
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    # Add host.docker.internal mapping to host gateway
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - fireflynet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - fireflynet
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  fireflynet:
    driver: bridge

volumes:
  postgres-data:
  rabbitmq-data: