version: '3.8'

services:
  fireflyarticles:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "21000:21000"
    # environment:
    #   # CORS
    #   - AllowedOrigins__0="http://localhost:3000"
    #   # GmailOAuth
    #   - GmailOAuth__ClientId=xxx
    #   - GmailOAuth__ClientSecret=xxxx
    #   - GmailOAuth__RedirectUri=http://localhost:21000/api/identity/auth/signin-google
    #   # AI Services
    #   - DeepSeek__ApiKey=xxxx
    #   - Ollama__ApiUrl=xxxx
    networks:
      - fireflynet
    depends_on:
      postgres:
        condition: service_healthy
    # Add host.docker.internal mapping to host gateway
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - fireflynet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  fireflynet:
    driver: bridge

volumes:
  postgres-data: