name: Build and Push Docker Images

on:
  push:
    branches: 
      - main
      - master
  workflow_dispatch:
# Commit message format to trigger the workflow:
# 
# Release Frontend Version X.Y.Z - Only builds and pushes the frontend
# Release Backend Version X.Y.Z - Only builds and pushes the backend
# Release App Version X.Y.Z - Builds and pushes both frontend and backend 
# 
jobs:
  check-commit:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
      build_frontend: ${{ steps.check.outputs.build_frontend }}
      build_backend: ${{ steps.check.outputs.build_backend }}
      build_app: ${{ steps.check.outputs.build_app }}
      version: ${{ steps.check.outputs.version }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Check commit message
        id: check
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MSG"
          
          if [[ "$COMMIT_MSG" =~ Release[[:space:]]+(Frontend|Backend|App)[[:space:]]+Version[[:space:]]+([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
            
            # Extract version from commit message
            VERSION=$(echo "$COMMIT_MSG" | grep -oP 'Version \K[0-9]+\.[0-9]+\.[0-9]+')
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "Extracted version: $VERSION"
            
            if [[ "$COMMIT_MSG" =~ Release[[:space:]]+Frontend ]]; then
              echo "build_frontend=true" >> $GITHUB_OUTPUT
            else
              echo "build_frontend=false" >> $GITHUB_OUTPUT
            fi
            
            if [[ "$COMMIT_MSG" =~ Release[[:space:]]+Backend ]]; then
              echo "build_backend=true" >> $GITHUB_OUTPUT
            else
              echo "build_backend=false" >> $GITHUB_OUTPUT
            fi
            
            if [[ "$COMMIT_MSG" =~ Release[[:space:]]+App ]]; then
              echo "build_app=true" >> $GITHUB_OUTPUT
              echo "build_frontend=true" >> $GITHUB_OUTPUT
              echo "build_backend=true" >> $GITHUB_OUTPUT
            else
              echo "build_app=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
            echo "build_frontend=false" >> $GITHUB_OUTPUT
            echo "build_backend=false" >> $GITHUB_OUTPUT
            echo "build_app=false" >> $GITHUB_OUTPUT
            echo "version=latest" >> $GITHUB_OUTPUT
          fi

  build-and-push:
    needs: check-commit
    if: needs.check-commit.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push backend image
      - name: Build and push backend image
        if: needs.check-commit.outputs.build_backend == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./BackendDotNet/FF.Articles.Backend
          push: true
          tags: |
            firefly26710/ffarticles-backend:latest
      # firefly26710/ffarticles-backend:${{ needs.check-commit.outputs.version }}

      # Build and push frontend image with environment variables from secrets
      - name: Build and push frontend image
        if: needs.check-commit.outputs.build_frontend == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./FrontendReact/ff-articles-frontend
          push: true
          tags: |
            firefly26710/ffarticles-frontend:latest
      # firefly26710/ffarticles-frontend:${{ needs.check-commit.outputs.version }}
          build-args: |
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
            NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }}
            NEXT_PUBLIC_APP_VERSION=${{ needs.check-commit.outputs.version }}
      
      # Trigger deployment webhook
      - name: Trigger deployment
        if: success()
        run: |
          curl -X GET ${{ secrets.WEBHOOK_URL }}