name: Manual Deploy

on:
  workflow_dispatch:
    
jobs:
  deploy-backend-to-server:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          if_key_exists: replace
      
      - name: Deploy to macOS server
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$SSH_HOST "cd /Users/liqiangwang/Repo/FireflyArticles/Deploy && docker-compose -f docker-compose.backend.yml up -d"

  deploy-frontend-to-server:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deployment
        if: success()
        run: |
          curl -X GET ${{ secrets.WEBHOOK_URL }}
