name: Manual Deploy

on:
  workflow_dispatch:
    
jobs:
  deploy-backend-to-server:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      
      - name: Deploy to macOS server
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$SSH_HOST "cd /Users/liqiangwang/Repo/FireflyArticles/Deploy && export PATH=/usr/local/bin:/opt/homebrew/bin:$PATH && docker compose -f docker-compose.backend.yml up -d"

  deploy-frontend-to-server:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deployment
        if: success()
        run: |
          curl -X GET ${{ secrets.WEBHOOK_URL }} --header 'Authorization: ${{ secrets.WEBHOOK_AUTH }}'
